<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NotePalWindows</RootNamespace>
    <AssemblyName>NotePal</AssemblyName>
    <ApplicationIcon>Assets\NotePal.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Kongzi.png" />
    <Resource Include="Assets\Newton.png" />
    <Resource Include="Assets\NotePal.ico" />
    <Resource Include="Assets\NotePalLogo.png" />
    <Resource Include="Assets\SpecialThemeA.notepalasset" />
    <Resource Include="Assets\SpecialThemeB.notepalasset" />
  </ItemGroup>
</Project>
